class ACL(object):

    def __init__(self, permissions_by_id: str=None) -> None: ...

    def _set_access(self, access_type: str, user_id: str, allowed: bool) -> None: ...

    def _get_access(self, access_type: str, user_id: str) -> bool:...

