from typing import SupportsFloat, Any



class GeoPoint(object):
    def __init__(self, latitude: supportFloat, longitude: SupportsFloat) -> None:...

    def longitude(self, longitude: SupportsFloat) -> None:...

    def latitude(self, latitude: SupportsFloat) -> None:...

    def radians_to(self, other: GeoPoint) -> float:...

    def kilometers_to(self, other: GeoPoint) -> float:...

    def miles_to(self, other: GeoPoint) -> float:...

#    def __eq__(self, other: GeoPoint)-> Any:...


