from typing import SupportsFloat, Any



class GeoPoint(object):
    def __init__(self, latitude: SupportsFloat, longitude: SupportsFloat) -> None:...

    @classmethod
    def _validate(cls, latitude: SupportsFloat, longitude, SupportsFloat):...

    @property
    def longitude(self):...
    
    @longitude.setter
    def longitude(self, longitude: SupportsFloat) -> None:...

    @property
    def latitude(self):...

    @latitude.setter
    def latitude(self, latitude: SupportsFloat) -> None:...

    def dump(self):...

    def radians_to(self, other: GeoPoint) -> float:...

    def kilometers_to(self, other: GeoPoint) -> float:...

    def miles_to(self, other: GeoPoint) -> float:...

    def __eq__(self, other: object)-> bool:...
