from typing import Union, Any, SupportsFloat, Tuple

import leancloud
from leancloud.object_ import Object
from leancloud.geo_point import GeoPoint


class Query(object):
    def __init__(self, query_class: Union[str, Object]) -> None:...

    @classmethod
    def or_(cls, *queries: Query) -> Query:...
 
    @classmethod
    def and_(cls, *queries: Query) -> Query:...

    @classmethod 
    def do_cloud_query(cql, *pvalues):...

    def first(self):...

    def get(self, object_id: str) -> Object:...

    def find(self):...

    def count(self):...

    def skip(self, n:int) -> Query:...

    def limit(self,n:int) -> Query:...

    def equal_to(self, key: str, value: Any):...

    def not_equal_to(self, key: str, value: Any):...

    def less_tan(self, key: str, value: Any):...

    def greater_than(self, key: str, value: Any):...

    def less_than_or_equal_to(self, key: str, value: Any):...

    def greater_than_or_equal_to(self, key: str, value: Any):...

    def contained_in(self, key: str, values: Union[List[Any],Tuple[Any]]) -> Query:...

    def not_contained_in(self, key: str, values: Union[List[Any],Tuple[Any]]) -> Query:...

    def contains_all(self, key: str, values: Union[List[Any],Tuple[Any]]) -> Query:...

    def exitst(self, key: str):...

    def does_not_exists(self, key: str):...

    def matched(self, key: str, regex: str, ignore_case: bool=False, muliti_line: bool=False):...

    def matches_query(self, key: str, value: Any):...

    def does_not_match_query(self, key: str, value: Any):...

    def matched_key_in_query(self, key: str, query_key: str, query: Query):...

    def matches_key_in_query(self, key: str, query_key: str, query: Query):...

    def does_not_match_key_in_query(self, key: str, query_key: str, query: Query):...

    def contains(self, key: str, value: Any):... 

    def startwith(self, key: str, value: Any):...

    def endwith(self, key: str, value: Any):...

    def ascending(self, key: str):...

    def add_ascending(self, key: str):...

    def descending(self, key: str):...
     
    def add_descending(self, key: str):...

    def near(self, key: str, point: GeoPoint):...

    def within_radians(self, key: str, point: GeoPoint, max_distance: SupportsFloat, min_distance: SupportsFloat=None):...

    def within_miles(self, key: str, point: GeoPoint, max_distance: SupportsFloat, min_distance: SupportsFloat=None):...

    def within_kilometers(self, key: str, point: GeoPoint, max_distance: SupportsFloat, min_distance: SupportsFloat=None):...

    def within_geo_box(self, key: str, southwest: Union[List, Tuple], northeast: Union[List, Tuple]):...

    def include(self, *keys: str):...

    def select(self, *keys: str):...
